### ISSUE TITLE
[COMMON] 3층 사물함 반납 시 비밀번호 등록 기능

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1059]
### 작업 설명

3층 사물함의 작동방식이 기존의 사물함과 다름에 따라서, 비밀번호 변경이 수월하게끔 서비스 기능을 구현해야 합니다.

예상되는 유저 사용 흐름은 다음과 같습니다.

1. 대여 시 3층 사물함의 유의사항 모달 및 확인 창 팝업
2. 대여 후 메모에 기존 사용자가 등록한(초기 시 1111) 비밀번호가 적혀 있음
3. 해당 메모를 보고, '비밀번호 변경방법' 을 통해서 본인이 사용하고자 하는 비밀번호로 변경 후 사용
4. 반납 시 본인이 사용하던 비밀번호를 '두 번' 입력하여 확인한 후에 반납 완료.

### 접근 방법

프론트의 경우에는 비밀번호를 1111로 수정하는 것을 유도할 수 있게끔 모달을 만들어 주시면 좋을 것 같습니다.
요청의 경우 반납 시에 비밀번호를 입력 받고,  그 값을 담은 요청을 서버에 날려주시면 될 것 같습니다.

백의 경우에는 프론트에서 요청과 함께 들고온 값을 해당 사물함의 메모에 넣어주는 API를 만들면 될 것 같습니다.

**Comment by Ssuamje** [comment]
3층에서 공유 사물함을 반납하는 경우에는 어떻게 해야할까요?
마지막 한명이 반납할 때 입력하게끔 해야 할까요?

**Comment by 42inshin** [comment]
> 

사난님 말씀대로 공유 사물함의 경우에 마지막으로 반납하는 사람이 입력하게 하는게 적절할 것 같습니다👍
