### ISSUE TITLE
[FE] 공유 사물함 대여 시작 안 했을 때 9999-12-30 나오는 이슈

### ISSUE THREAD

**Issue by oyhoyhk** [innovationacademy-kr/42cabi#1073]
### 버그 설명

공유 사물함 조회 할 때

특정 유저는 9999-12-31 날짜가 나오는 반면
어떤 유저는 아무런 날짜가 나오지 않음

### 재현 방법

main서버 2층 89번 94번 자리 확인

### 기대했던 정상 동작

대여 시작 안 했으면 날짜 나오면 안 됨

**Comment by junyoung2015** [comment]
assignees 들과 리뷰 중 주석 발견했습니다.
