### ISSUE TITLE
[COMMON] 포팅으로 인한 변경사항 논의

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#1080]
### 작업 설명

스프링 포팅으로 인해 생기는 변경사항들에 대해 기록하고 논의하는 이슈입니다.

### 접근 방법

추후에 변경될 사안이라도 해당 이슈에 적어놓고 실제로 변경될 시점에 새로운 이슈를 파서 해결합니다.

**Comment by eunbi9n** [comment]
admin에서 사용 중인 `/api/admin/search/:intra_id`에 관해 논의하고 싶습니다.

현재 방식으로는 한 번의 api 요청으로 해당 intraId를 포함하는 유저의 ban 정보 + 사물함 정보를 `UserCabinetInfoPagenationDto`로 가져오고 있습니다.
너무 많고 일관성이 없는 정보를 한 번에 가져오는 것 같아, 해당 dto를 수정하거나 두 번의 api로 나눠서 정보를 가져오는 것은 어떤지에 대해 얘기가 나왔는데 이에 대해 프론트 분들과 함께 얘기 해보고 싶습니다!

**Comment by oyhoyhk** [comment]
이 api를 두 개로 나누었을 때 그 두 개를 각각 다른 곳에서도 사용을 한다면 나누는 것이 좋겠지만

이 검색 기능만을 위한 api라면 굳이 나눠서 두 번의 요청을 해야 할 필요가 있나? 싶습니다.

p.s) 사용 정지 유저를 검색했을 때 사용 정지에 대한 정보가 안 넘어 오는 것 같습니다
<img width="794" alt="Screen Shot 2023-05-03 at 7 32 20 PM" src="https://user-images.githubusercontent.com/55866366/235892953-598848cc-6c83-4624-9720-2eabd9fb2b7d.png">
<img width="403" alt="Screen Shot 2023-05-03 at 7 32 15 PM" src="https://user-images.githubusercontent.com/55866366/235893132-29382eb4-2650-4114-adc3-4dd0966ae3a1.png">
<img width="1278" alt="Screen Shot 2023-05-03 at 7 31 05 PM" src="https://user-images.githubusercontent.com/55866366/235893156-736ce195-cd11-4dc3-9637-ccb930d06f8d.png">

**Comment by eunbi9n** [comment]
> 제 개인적인 의견입니다

`/api/search/user/overdue`가 어떤 정보를 넘겨주는지를 확인해봤는데 해당 api에서 넘겨주는 정보는
`intra_id`, `cabinet_id`, `location(ex. 1f-100)`, `overdueDays`로
 연체중인 유저 리스트를 반환하기 보다는 `lent`의 정보들과 더 밀접해보입니다.
 따라서 해당 api나 dto 이름에 관해 수정하는 것이 좋을 것 같습니다.

**Comment by Ssuamje** [comment]
이후에 회의에서 얘기할 사항으로 채택되어서 이슈는 닫겠습니다..!
