### ISSUE TITLE
[FE] 본인 페널티 여부 확인할 수 있는 정보 창 

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1143]
### 작업 설명

<img width="840" alt="스크린샷 2023-05-30 오후 1 20 48" src="https://github.com/innovationacademy-kr/42cabi/assets/105692206/0a437ccc-1b73-4443-8cdd-743f4bd792b8">
현재 페널티 여부를 유저 본인이 확인할 수 있는 방법은 대여를 시도하는 방법만 있는 것으로 알고 있는데,
이에 대해서 본인의 상태를 알 수 있는 정보 창이 있으면 좋을 것 같습니다..!

### 접근 방법

프론트 작업.

**Comment by 42inshin** [comment]
<img width="350" alt="image" src="https://github.com/innovationacademy-kr/42cabi/assets/72684256/df63b66f-b7b0-4211-ac51-5a78663107a4">

로그인 하자마자 보여주려면 myInfo 에서 보내주는 데이터에 패널티 시간도 같이 주시면 해결할 수 있을 것 같습니다!
