### ISSUE TITLE
[BE] SPRING controller 기존 API 구현

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1146]
### 작업 설명

기존에 Nest.js에 있는 API들을 그대로 구현합니다.
포팅을 우선하는 작업입니다.

### 접근 방법

기존 담당 :
auth - @sanan @sichoi 
cabinet - @sanan 
user - @eunbikim 
lent - @dongglee @huchoi 

새 담당:
렌트 컨트롤러 API 붙이기 - @jpark2 @sanan @daewoole @wchae 
유저 어드민 컨트롤러 - @jpark2 
통계 컨트롤러 - @daewoole 
사물함 컨트롤러 - @sanan @wchae 
인증 컨트롤러 - @daewoole @jpark2

기존 담당 + 새 담당으로 업무 분장 나뉜 것이라고 생각하시면 될 것 같습니다..!

**Comment by Z1Park** [comment]
이슈에 왜 안보이는지 모르겠지만, 어드민 유저 작업해서 `be/spring/admin_user/#1146`으로 브랜치 파서 push 했습니다...
테스트 코드는 아직 작성이 안되어있습니다.
