### ISSUE TITLE
[BE] Admin 연체일 표기일이 0일로 나타나는 부분

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1154]
### 버그 설명

연체일이 0일인 것으로도 표기됩니다.
<img width="445" alt="image" src="https://github.com/innovationacademy-kr/42cabi/assets/105692206/5471f7d5-6222-49f7-8286-e85917781596">

### 재현 방법

어드민 들어가보기

### 기대했던 정상 동작

0일 X
1일 O

**Comment by Z1Park** [comment]
#1213 과 동일 이슈로 close 하겠습니다.
