### ISSUE TITLE
[BE] Spring test db 만드는 방법 변경

### ISSUE THREAD

**Issue by leedonggyu1848** [innovationacademy-kr/42cabi#1171]
### 작업 설명

sql쿼리를 사용하면 코드가 변경되거나, 날짜같은 관리하기 힘든 값에 대해서 변경이 유연하지 못하다는 생각이 들어 바꾸는 것이 좋아보임

### 접근 방법

test db를 만드는 방식을 ddl쿼리를 이용하는 방식이 아니라
table은 hibernate가 자동으로 만들도록 하고, 데이터 java로 넣을 수 있는 코드를 따로 작성하여 필요한 부분에서 가져다가 사용할 수 있도록 변경

**Comment by Ssuamje** [comment]
근데 이 부분에 대해서 ddl과 별도의 create하는 부분을 나눠서 켜질때 작동하도록 하는 방식이 있기는 한데.. 이 방법보다 코드부에서 직접 넣는게 더 오래걸리거나 하지는 않을까요..??

근데 주석이나 가독성을 생각해보면..🤔

**Comment by leedonggyu1848** [comment]
느려지긴 할 거 같은데 저희 코드가 변경되었을 때 코드부로 직접 넣는 게 오류를 찾기 쉬워지지 않을까 하는 생각이 들긴 합니다
