### ISSUE TITLE
[BE] SPRING 테스트 코드 재작성

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1187]
### 작업 설명

Unit 테스트, 통합 테스트, E2E 테스트를 구분하여 일관성 있게 재작성합니다.
이미 작성된 테스트들에 대해서는 필요한 부분만 재사용합니다.

### 접근 방법

유닛 테스트 : 가장 낮은 수준의 객체들 부터 테스트를 동작 테스트를 작성하고, 그를 주입받는 클래스들은 Mock을 주입받아서 동작하게끔 작성합니다.

**Comment by enaenen** [comment]
Cabinet : @Ssuamje
Lent : @enaenen
Member: @Z1Park
Auth : @LeeDaeWook

**Comment by enaenen** [comment]
Cabinet : @LeeDaeWook   @enaenen 
Lent : @enaenen 
Member: @Z1Park 
Auth : @Ssuamje
