### ISSUE TITLE
[BE] SPRING 도메인 유효성 검사 적용 및 @Validation 적용

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1188]
### 작업 설명

도메인 객체들의 생성 시점에 대해서 유효한 값을 갖게끔 spring-boot-validation을 이용하여 설정합니다.

### 접근 방법

어노테이션을 이용한 객체 유효 값 표현

**Comment by enaenen** [comment]
Cabinet : @Ssuamje 
Lent : @enaenen 
Member: @Z1Park 
Auth : @LeeDaeWook
