### ISSUE TITLE
[COMMON] 스프링 포팅 + 프론트 병합

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1191]
### 작업 설명

포팅된 스프링 백엔드를 프론트엔드와 합칩니다.

### 접근 방법

도전..

**Comment by eunbi9n** [comment]
### BE TODO
- [ ] /v4/admin/search/cabinets?visibleNum={number} -> `floor` optional 쿼리 추가
- [ ] /v4/admin/statistics/lent-histories?startDate={date}&endDate={date} -> 쿼리로 받는 값 Date 객체 아니고 number로 변경
- [ ] 정적 Master email 넣기
