### ISSUE TITLE
[FE] admin 사물함 상태 변경 테이블 추가

### ISSUE THREAD

**Issue by seong-hui** [innovationacademy-kr/42cabi#1396]
### 작업 설명

admin home에 사물함 상태 변경 예약을 걸어놓은 사물함을 보여주고자합니다. 

### 접근 방법

사물함 변경 예약을 걸어놓은 사물함을 서버로부터 받아서 기존의 다른 사물함 테이블이 보여지는 형식과 같게 보여줄 것입니다.

**Comment by Ssuamje** [comment]
관련한 이슈가 있으므로 해당 부분에 코멘트로 업데이트 해두겠습니다~
