### ISSUE TITLE
[COMMON] 오픈예정 / 사용가능에 대한 UI 애매, 미구현 및 오늘/내일 열리는 PENDING 사물함에 대한 정보 부재

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#1448]
### 버그 설명

<img width="1687" alt="스크린샷 2023-11-27 오후 3 20 13" src="https://github.com/innovationacademy-kr/42cabi/assets/105692206/c340bd50-bbdb-4318-9cb7-f641d418d9f6">
현재 상황에서는 AVAILABLE과 PENDING이 같이 나타나는데, 프론트적으로 구분하는 구현이 부재하므로 이후 작업으로 미룹니다.
+
오늘 ,내일 열리게 되는 PENDING 사물함에 대해서 프론트 && 백에서 구분이 이뤄지지 않고 있으므로, 사용자 이용에 혼선이 있을 수 있습니다. 

### 재현 방법

dev에서 발생 중

### 기대했던 정상 동작

최대한 빠른 시간 내에 작업합니다.

**Comment by enaenen** [comment]
메서드 이름 수정 (Pending -> Available)+ 현재는 사용 가능 사물함만 보이도록 했는데 추후 기능 추가

**Comment by Ssuamje** [comment]
아까 dev보니까 해결된 것 같던데 맞나요?

**Comment by Z1Park** [comment]
일단 백에서는 오늘 열리는 사물함만 가져오기는 하는데, UI 측면에서도 오늘 열리는 것과 내일 열리는 것에 대한 구분이 필요할 듯 합니다.
