### ISSUE TITLE
블랙홀 처리 관련 예외사항 발생

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#191]
### 버그에 대한 설명

1. 새 피시너가 블랙홀의 빠진 유저와 동일한 login을 할당 받아 생기는 문제
블랙홀에 빠진 유저의 login과 동일한 이름을 피시너가 새로 할당받기 때문에 db에서 이 둘을 구분할 수 없습니다.
따라서 API Request를 보낼 때 새 피시너의 정보를 가져오게 되므로 기존 정보와 충돌이 발생합니다.

2. Learner 정보가 없는 본과정 유저
막 본과정에 들어와서 Learner 정보가 없는 유저가 존재할 수 있을 것 같습니다.(정확히는 확인해봐야할듯...)

3. 보컬분들도 db에 존재
보컬분들도 db에 존재하는 경우가 있습니다. 이 경우 현재 로직에서는 해당 유저를 삭제하도록 되어있는데
삭제하는게 맞을지 놔두는게 맞을지 고민을 해봐야할 것 같습니다.

4. 블랙홀에 빠진 유저를 삭제하는게 맞을지..?
1번과 같은 문제를 방지하기 위해서 블랙홀에 빠진 유저를 삭제하기 보다는 login을 [blackholed][login]과 같은 형태로 login을 수정하면 어떨까요?

### 하고싶은 말, 근황 등등.. (이건 안적으셔도... 하하)
정말 생각지도 못한 예외가 많군여... 😇

**Comment by sichoi42** [comment]
### 42에서 유저의 정보가 완전히 삭제되면 해당 유저가 가지고 있었던 user_id도 새로 할당 가능
- 블랙홀에 빠지고 정보도 삭제되신 jeokim님의 user_id를 jeonghwk님이 새로 할당받은 것 같아요.
- login 뿐만아니라 user_id도 새로 할당이 되기 때문에 인트라에서 삭제된 유저의 정보를 db에 유지하기엔 무리가 있을 것 같습니다.
- 따라서 4번에서 블랙홀에 빠진 유저를 유지하고 blackholed값을 true로 바꾸기 보다는 아예 삭제하는게 좋을 것 같습니다!

### Staff의 정보는 삭제하지 않음

**Comment by eunbi9n** [comment]
user_id까지 새로 할당이 된다면 blackholed 필드로 유저를 유지하기엔 sichoi님의 말씀대로 문제가 있을 것 같습니다!

하지만 블랙홀에 빠진 유저를 삭제할 경우,
- admin 페이지 상에서 사물함을 사용하였던 유저의 intra_id가 뜨지 않는 현상은 어떻게 해결되는지 궁금합니다!
- admin에서 사용자를 검색했을 때 
   1. 4월에 기존 jeokim님이 사물함을 빌리신 것으로 log가 남아있음
   2. 새로운 jeokim님이 11월에 들어오셔서 사물함을 빌리면 기존 jeokim님과 같은 user_id와 intra_id로 새로운 log가 남음
   
  그렇다면 admin 페이지에서 검색할 때 같은 사용자로 인식을 하지 않을까 싶습니다!

위와 같은 이유로 유저를 바로 삭제하는 방법을 사용하기보단, 새로운 방법을 좀 더 의논해보는게 좋을 것 같다고 생각합니다.

**Comment by joohongpark** [comment]
user_id까지 재할당이 되는군요...

jeokim님의 user_id를 jeonghwk님이 새로 할당받은 경우에 대해선 블랙홀에 빠진 유저는 원칙적으로 42 OAuth를 통한 로그인이 되지 않으니, 만약 블랙홀에 빠진 유저의 user_id가 재 할당이 일어나 새 42 계정을 부여받았으면 재 할당을 받은 유저가 로그인을 할 때라면 기존 로그를 지워버리고 `blackholed` 필드를 `true`로 바꾸는건 어떠신가요?=
