### ISSUE TITLE
DTO 정리

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#215]
기존 DTO를 전반적으로 수정합니다.

- [ ]  파일 네이밍 통일
- [ ] 변경할 모듈에 맞는 위치로 이동.
- [ ] 중복되서 사용되는 부분 상속받도록 수정.

**Comment by joohongpark** [comment]
DTO는 프로젝트 폴더 내 `src` 내 `dto` 폴더에 만들어 두겠습니다.
