### ISSUE TITLE
ERD를 토대로 DB 테이블 구축 및 기존 데이터 이관

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42cabi#234]

**Comment by sichoi42** [comment]
# user

### 변경사항
user테이블 필드에서 auth를 state로 변경했습니다.
state 필드로 블랙홀에 빠진 유저 판단이 가능하여 is_blackholed 필드는 삭제했습니다.

# cabinet


# lent

### 외래키 관련
lent_user_id에 대응하는 user_id가 user 테이블에서 update될 때 종속적으로 바뀌고
user를 삭제하는 것은 정의되지 않은 동작으로 간주해 delete 시도시 삭제를 못하도록 설정했습니다. (on update cascade)
ex1) user_id가 1 -> 2로 업데이트되면 lent_user_id도 1->2로 변경.
ex2) user_id에 대응하는 row 삭제 시도시 오류 발생.
cabinet_id도 동일하게 적용됩니다.



# lent_log

### 변경사항
lent_type은 log_cabinet_id를 통해 접근 가능하므로 lent_log 테이블 필드에서 삭제했습니다.

### 외래키 관련
log_user_id에 대응하는 user_id가 user 테이블에서 update될 때 종속적으로 바뀌고
user를 삭제하는 것은 정의되지 않은 동작으로 간주해 delete 시도시 삭제를 못하도록 설정했습니다. (on update cascade)
ex1) user_id가 1 -> 2로 업데이트되면 log_user_id도 1->2로 변경.
ex2) user_id에 대응하는 row 삭제 시도시 오류 발생.
cabinet_id도 동일하게 적용됩니다.


ban_user

### 건의사항
새 사물함 정책에서는 연체된 날짜만큼 누진적으로 차단 기간(업보제)이 정해지니
ban_user 테이블을 만들지 않고 ban_log 테이블을 만드는게 어떨까요?
밴이 되면 기존 ban_log에서 ban되어있던 시간의 총 합 만큼 빌리지 못하게 하면 될 것 같습니다!
또한 현재 밴이 된 상태는 user테이블의 state로 판단 가능합니다.

### 외래키 관련
ban_user_id에 대응하는 user_id가 user 테이블에서 update될 때 종속적으로 바뀌고
user를 삭제하는 것은 정의되지 않은 동작으로 간주해 delete 시도시 삭제를 못하도록 설정했습니다. (on update cascade)
ex1) user_id가 1 -> 2로 업데이트되면 ban_user_id도 1->2로 변경.
ex2) user_id에 대응하는 row 삭제 시도시 오류 발생.
cabinet_id도 동일하게 적용됩니다.
