### ISSUE TITLE
신규 기능 개발(Cabinet)

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#256]
새로운 기능을 추가한 cabinet 모듈 제작

**Comment by sichoi42** [comment]
은비킴님 Cabinet의 activation을 변경하는 repository 함수 구현 부탁드려요! (CabinetService에서 호출 가능하면 좋을 것 같습니다.)

`abstract updateCabinetActivation(cabinet_id: number, activation: number): Promise<void>;`

**Comment by eunbi9n** [comment]
> 은비킴님 Cabinet의 activation을 변경하는 repository 함수 구현 부탁드려요! (CabinetService에서 호출 가능하면 좋을 것 같습니다.)
> 
> `abstract updateCabinetActivation(cabinet_id: number, activation: number): Promise<void>;`
Service에도 같은 이름으로 구현해놓았습니다!
