### ISSUE TITLE
추가/변경/삭제가 필요한 Dto/Entity 정리

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#268]
신규 기능을 개발하시다가 추가/변경/삭제가 필요한 Dto/Entity가 있을 것 같아요.
그런 사항들을 여기에 정리해두면 좋을 것 같습니다!!

# User

- [x] 유저가 대여했는지 아닌지 확인하려면 `UserSessionDto`에 is_lent 필드가 필요합니다.

# Cabinet

- [x] 대여할 때 잔여 자리가 있는지 확인하려면 현재 사물함을 대여하고 있는 인원 정보가 
`CabinetDto`에 추가되야할 것 같습니다. 뿐만아니라 DB에도 해당 필드가 필요할 것 같네요.

- [x] 개인 사물함일 때는 max_user가 1로 설정되어야 /api/lent 구현이 편할 것 같습니다!

- [x] `CabinetInfoResponseDto`에서 

> is_lent: boolean; // 대여했는지 여부 - 기존 activation

라고 되어있는 부분이 있는데 activation은 사물함이 고장났는지(0), 밴된 유저가 쓰던 사물함이라 임시 비활성화가 됐는지(2), 정상 이용 가능한 사물함인지(1)를 나타내므로 이 필드와 별개로 필요합니다. 들어간다면 `CabinetDto`나 `CabinetExtendDto`에 들어가면 좋을 것 같습니다!

**Comment by joohongpark** [comment]
사용자의 세션을 저장하는 `UserSessionDto` 에 대여 정보를 담을 필요가 있을까요?

**Comment by eunbi9n** [comment]
오 좋습니다!!
근데 Entity에도 따로 추가해야 하나요? lent dto에 있는 users 정보를 이용해서 구할 수 있지 않을까 싶습니다👀

**Comment by sichoi42** [comment]
헉 두분이 말씀하신게 맞네요!

> 유저가 대여했는지 아닌지 확인하려면 UserSessionDto에 is_lent 필드가 필요합니다.
요건 UserDot에 저장하도록 하고
> 대여할 때 잔여 자리가 있는지 확인하려면 현재 사물함을 대여하고 있는 인원 정보가 CabinetDto에 추가되야할 것 같습니다. 뿐만아니라 DB에도 해당 필드가 필요할 것 같네요.
요건 LentDto를 통해 관리하면 될 것 같습니다!

**Comment by sichoi42** [comment]
UserDto에 is_lent 필드를 추가해서 중간에 값이 업데이트되면 jwt 인증이 되지 않기 때문에 토큰을 재발급해야 합니다.
따라서 대여했는지 여부 확인은 is_lent를 통해서가 아닌 그때그때 Lent Table에서 조회해서 확인하겠습니다.

**Comment by eunbi9n** [comment]
LentDto의 `users` 삭제
LentDto에 `user_id`, `intra_id` 추가
CabinetDto에 `activation`추가 (0: 고장 1: 사용가능 2: ban 3: 대여중)
CabinetInfoResponseDto의 `lent_info?: LentDto` -> `lent_info?: LentDto[]`
CabinetInfoResponseDto의 `is_lent` 삭제 -> 기존 is_lent의 역할은 CabinetDto의 activation 활용
MyCabinetInfoResponseDto의 `lent_info?: LentDto` -> `lent_info?: LentDto[]`
MyCabinetInfoResponseDto의 `is_lent` 삭제 -> 기존 is_lent의 역할은 CabinetDto의 activation 활용
