### ISSUE TITLE
샘플 데이터 삽입 이슈

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42cabi#296]
샘플 데이터를 추가하거나 변경할 때 해당 이슈에 기록합니다.

**Comment by joohongpark** [comment]
프론트앤드 분들께 사물함 샘플데이터를 삽입해달라는 요청이 있어 삽입하였습니다.
 - 기본적으로 기존 사물함 데이터 사용
 - 2층 한정 공유사물함 지정

**Comment by sichoi42** [comment]
1. TODO
샘플데이터 삽입 후 공유를 용이하게 하기 위해서 기존 방법 대신 volume에 저장하도록 수정 필요
