### ISSUE TITLE
/v3/api/lent/{cabinet_id} 응답 상태 분류 요청

### ISSUE THREAD

**Issue by HyeonsikBae** [innovationacademy-kr/42cabi#369]
아래 세가지 상황에 동일한 응답코드 403을 받고 있습니다.
1. cabinet_status === BANNED
2. cabinet_status === BROKEN
3. 공유사물함 대여 후, 72시간 내 반납한 유저의 사물함 대여

FE에서 세 가지 상황에 대한 분류를 할 수 없어 response body에 이를 분류할 수 있는 추가 데이터가 필요할 듯 합니다
현재는 응답코드에 따라 띄워줄 경고 메세지를 분류하고 있습니다. (400, 403, 409, 418, 그 외)
협의 후 기능 수정이 필요할 것 같습니다

@joohongpark @eunbi9n @aseungbo @gyutato

**Comment by eunbi9n** [comment]
body에 user의 `state`와 `cabinet_status` 정보를 담아 보내드리면 그걸로 처리를 하시면 될 것 같습니다!!

**Comment by HyeonsikBae** [comment]
lent 실패 시, status code에 따라 출력할 메세지를 switch 문으로 나눠서 사용하는 중입니다.
BE단에서 error를 보내줄 떄, response body 내 message 포함시켜 주시면 에러의 경우 바로 메세지 출력하면 될 것 같습니다.

상황에 따른 출력 메세지 요청 드립니다 :)
- 400 : 이미 대여중인 사물함이 있는 경우
  `"🚨 이미 대여중인 사물함이 있습니다 🚨"`
- 403 : 관리자에 의한 임시 밴 사물함인 경우
  `"🚨 해당 사물함은 비활성화된 사물함입니다 🚨"`
- 403 : 관리자에 의한 고장 사물함인 경우
  `"🚨 해당 사물함은 고장난 사물함입니다 🚨"`
- 403 : 공유사물함 대여 후 72시간 내 반납으로 인한 페널티로 대여하지 못하는 경우
  `"🚨 페널티로 인해 현재 사물함 대여가 불가능합니다 🚨"`
- 409 : 잔여 자리가 없는 경우
  `"🚨 해당 사물함에 잔여 자리가 없습니다 🚨"`
- 418 : 동아리 사물함을 대여 시도한 경우
  `"🚨 해당 사물함은 동아리 전용 사물함입니다 🚨"`
