### ISSUE TITLE
탭 이탈하면 localStorage 유저 정보 삭제

### ISSUE THREAD

**Issue by gyutato** [innovationacademy-kr/42cabi#408]
로그아웃 없이 탭을 종료하면 localStorage에는 유저 정보가 그대로 남아 있습니다. 

이 때 cabidev 에 접속하면 로그인하지 않아도 페이지에 접근되는 문제가 발생하며, 로그인은 안된 상태이기 때문에 대여 및 반납 등은 불가능합니다.

**Comment by sichoi42** [comment]
# 1. 문제 발생원인
<br>
정확한 문제는 `localStorage`에 유저정보가 남아있고 + `accessToken`을 가지고 있는 상태로 한 번도 로그인하지 않은 `cabidev`에 접속했을 때 발생합니다. 
<br>
토큰을 가지고 dev에 접속하면 `accessToken`이 만료되지 않았으므로 로그인 없이 `JWT` 인증을 통과하여 대여 페이지로 넘어갑니다.
Cabi는 최초 로그인 시 `user` 테이블에 값이 추가되는 방식이므로 이 상태로 대여를 시도하면  
DB에 존재하지 않은 유저의 `user_id`로 대여 요청을 하게 되고, 그렇게 되면 `queryFailedException`이 발생합니다.
`queryFailedException`가 발생하면 해당 에러 메시지가 `InternalServerException`으로 프론트에 전달되어 위와 같은 상황이 발생합니다.

<br><br>
# 2. 서비스 오픈날 문제 발생 가능성
<br>
V3는 DB를 새로 초기화하고 서비스를 오픈하므로, 만약 사용자가 기존 V2 메인 서비스에서 로그인을 하고, 로그아웃을 하지 않은 채로 
새로 오픈되는 V3에 접속하게 되면 위와 같은 문제가 발생할 가능성이 있습니다. 
따라서 `Backend`에서 생성되는 토큰의 이름을 `accessToken` -> `access_token`으로 변경하여 
V2에서 생성된 토큰을 그대로 V3에 들고가더라도 인증하는 토큰의 이름이 달라졌으므로 토큰이 없다고 판단해 로그인 페이지로 리다이렉트 되도록 유도하겠습니다.
