### ISSUE TITLE
floor 이동 시, 약간의 로딩이 걸리는 시간 동안에 대한 처리

### ISSUE THREAD

**Issue by aseungbo** [innovationacademy-kr/42cabi#413]
#### 상황
- 2층인 상태에서 4층 클릭 시 api 응답을 받아 렌더링될때까지 250ms 정도의 시간이 필요합니다.

**Comment by HyeonsikBae** [comment]
@sichoi42 
첫 페이지 로딩 될 때, 캐비넷 정보 호출하는 api가 늦게 응답오는 것과 같은 현상으로 보입니다.
FE에서 대응할 수 있는 방법은 아래 정도로 생각됩니다.
- spinner와 같은 애니메이션으로 로딩 중임을 알리기
- 컴포넌트 우선 렌더 후 데이터 삽입 (section map이 모두 유사하게 생겨 큰 의미가 없을 것 같습니다.)

sichoi님과 함께 확인한 결과, BE의 쿼리문 로그를 출력하지 않으니 시간이 유의미하게 줄어드는 것으로 확인됩니다.
추가로 쿼리 최적화가 가능한지 확인해주시면 감사하겠습니다~
