### ISSUE TITLE
공유사물함 방 제목, 메모장 값을 수정했을 때 이전에 설정한 값이 잠깐 깜빡거리는 현상

### ISSUE THREAD

**Issue by aseungbo** [innovationacademy-kr/42cabi#417]

**Comment by gyutato** [comment]
setTextValue가 axios 호출문 내부에서 실행되어, 비동기처리로 인한 시간차가 발생하는 것 같습니다.

setTextValue를 axios 호출문 내부에서 부르지 않고, 상단에서 먼저 호출하여 setState를 한 다음 **axios 호출이 실패했을 경우에만** 이전 textValue로 바꾸는 방식을 시도해보려고 합니당

또는 textValue가 언마운트될 때 무조건 빈 칸("")으로 바뀌었다가 업데이트된 값으로 다시 마운트 되는 방식도 생각해볼 수 있을 것 같습니다.
