### ISSUE TITLE
SET_EXPIRE_AVAILABLE 일 경우 색이 흰색으로 나오는 오류

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#430]
<img width="309" alt="스크린샷 2022-10-10 오후 8 30 14" src="https://user-images.githubusercontent.com/63849465/194859118-b5f97d4d-a1bc-4733-8b73-f552585b8ebc.png">

cabinet_status가 SET_EXPIRE_AVAILABLE일 경우 여전히 색이 흰색으로 나옵니다!
default 값으로 나오는 것 같습니다.

**Comment by HyeonsikBae** [comment]
@sichoi42 
/frontend_v3/src/components/atoms/buttons/CabinetBoxButton.tsx Line:58
|| 연산자로 구분된 조건을 다른 case로 나눠주시면 될 것 같습니다
