### ISSUE TITLE
로그 관리 기능 추가

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#434]
로그에 관련된 기능을 추가합니다.

**Comment by joohongpark** [comment]
- 컨트롤러, 서비스에서 호출여부를 확인하는 로그 : debug 로 출력
- 메일 송부와 같은 것은 log로 출력해서 stdout 으로 출력하자.
    - PM2가 로그화 시켜서 저장하기 때문에 궂이 파일로 저장 안해도 될 듯?
- 에러가 발생했을 때에는 error로 출력하게 하자.
- 불필요한 로그출력은 제외하자.
- 로거 객체에서 사용할 메소드 : `debug`, `log` , `error`
- 배포모드 : `log` , `error` 만 활성화
- 그 외 : `debug`, `log` , `error` 활성화
- 활성화 여부 : env 로 관리
- env → yaml 변경?

**Comment by eunbi9n** [comment]
https://docs.nestjs.com/techniques/configuration
