### ISSUE TITLE
API로 전달되는 Date 객체 KST로 수정

### ISSUE THREAD

**Issue by gyutato** [innovationacademy-kr/42cabi#452]
<img width="286" alt="스크린샷 2022-10-14 오후 4 43 44" src="https://user-images.githubusercontent.com/94846990/195791027-81eb1916-04ea-4af6-9057-92bc2bf80c27.png">

16:42분에 대여했는데, API 응답으로 받아온 데이터 상으로는 위 사진과 같습니다. 원인이 뭔지 확실하진 않지만... 가능하다면 KST로 수정 부탁드립니다 ~!

**Comment by sichoi42** [comment]
이 부분에 대해서 고민을 좀 해봤는데 Javascript에 저장되는 `Date`객체는 `KST`로된 시간을 집어 넣어도 자동으로 `UTC`로 변환을 시켜버리는 것 같습니다 ㅠㅠ..  그래서 실제 DB 상에는 KST로된 시간도 Javascript의 Date 타입으로 넣으면 UTC로 바뀌어버립니다.

`Date` 대신 string`으로 관리하는 방법도 있겠지만 기존에 정의되어 있는 Front와 Back의 DTO의 타입을 모두 string으로 바꿔줘야하고, 이에 따라 포맷도 다 맞춰줘야해서 공수가 많이 들어갈 것 같습니다.
그래서 최종적으로 사용자에게 시간 정보를 뿌려줄 때만 KST로 변환하여 뿌려주는게 어떨까요?

이런 문제 때문에 보통 Node 기반 프로젝트에서는 `moment-timezone`이라는 npm 모듈을 사용한다고 합니다.
````
// lent_time is Date Object
moment(lent_time).tz('Asia/Seoul').format('YYYY-MM-DD HH:mm:ss');
````

위와 같은 방식으로 Date타입의 날짜를 KST로 변환한다음 적절한 포맷팅을 거칠 수 있습니다 😊
