### ISSUE TITLE
42Cabi 새로운 서비스 이용 가이드 영상 제작

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#456]
`Bird Eats Bug`라는 익스텐션을 사용하면 Chrome 위에서의 작업들을 녹화할 수 있습니다.

이를 이용하여 이용 가이드 영상 제작을 하면 좋을 것 같습니다!

아래는 사용 예시입니다 😊

[c42b3bb5-403a-40b8-88b5-1014b0a9ba7a.webm](https://user-images.githubusercontent.com/83565255/195866910-08fd976c-7b7f-4f63-8ff9-7cd8677004ac.webm)

**Comment by aseungbo** [comment]
영상에  필요한 웹 화면만 부분적으로 녹화되서 좋은 것 같아요!! 👍
