### ISSUE TITLE
[DDL] ban_log의 관계 설정에 관하여

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#461]
기존에 skim님의 의견에 따라 `lent_log`와 `ban_log`의 관계 설정을 해제하기로 결정을 했었습니다.

skim님의 의견
```
- user와 cabinet이 삭제/업데이트 되었다고 해서 대여를 한 기록이 삭제/업데이트 되는 정보가 아니기 때문에 로그 관련은 FK를 끊는 것이 좋다.
- 현업에서도 로그는 삭제하지 않고 쌓아두는 편이다. (많이 쌓아두면 서비스의 규모에 대한 어필 가능)
```
이 외에도 유저가 블랙홀에 빠지면 해당 유저의 정보를 삭제처리하고 `lent_log`를 통해 추후 확인 가능하도록 합의한 부분도 있어
`lent_log`에 관해서는 저도 이 의견에 동의를 합니다. 

그러나 `ban_log`의 경우에는 그대로 `user` 테이블과의 관계를 유지하는게 좋을 것 같아서 의견을 제시하고자 합니다.

그렇게 생각한 근거는 다음과 같습니다.

1. `ban_log`는 로그를 쌓아두는 목적이 아닌 연체된 사용자에게 패널티를 주는 용도이다.
v1~v2에서는 `ban_user`로 영구밴된 유저의 정보를 기록했지만, v3에서는 영구밴이 사라지고 연체된 사용자에게 누적 패널티를 주는 방식으로 변경되었습니다. 그에 따라 `ban_user` 테이블의 이름도 `ban_log`로 변경되었고 `ban_log`에서 누적 연체기한을 계산해서 패널티를 주는 방식으로 동작합니다.
즉, `ban_log`는 이름만 로그 테이블이지, 실제로 로그를 쌓아두는 목적의 테이블이 아닙니다.

2. 블랙홀에 빠진 유저 관련
블랙홀에 빠진 유저의 정보는 기존 처럼 `user_id`와 `intra_id`를 변경하는 방식이 아니라 해당 유저의 정보를 DB에서 삭제처리하는 것으로 변경했습니다.
그런데 만약 해당 유저가 기존에 연체를 한 적이 있어 `ban_log`에 해당 기록이 남아있고, 추후 해당 유저의 `intra_id`나 `user_id`를 다른 유저가 할당을 받는다면 그 유저에게 패널티가 잘못 가게 되는 문제가 있습니다.(`data integrity` 문제)
`ban_log`와 `user`의 관계를 유지하고 `on delete cascade`를 달아주면 유저가 삭제될 때 `ban_log`도 같이 삭제가 되어 이런 문제를 쉽게 해결할 수 있습니다.

**Comment by joohongpark** [comment]
동의합니다!

**Comment by sichoi42** [comment]
은비킴님도 동의를 하셔서 그럼 `ban_log`와 `user`와의 관계는 유지하는 것으로 수정하겠습니다!
