### ISSUE TITLE
공유사물함 반납 시, 타이틀과 메모 초기화되지 않는 버그

### ISSUE THREAD

**Issue by HyeonsikBae** [innovationacademy-kr/42cabi#476]
## 버그사항이 담긴 제목
공유사물함 반납 시, 타이틀과 메모가 초기화되지 않는 버그가 있습니다.

### 버그에 대한 설명
동시에 여러 사람이 공유사물함을 대여할 경우, 최대 인원이 3명임에도 불구하고 더 많은 인원이 공유사물함을 대여하게 됩니다.
이 때, 사물함의 타이틀과 메모 변경 후 모든 대여자가 사물함을 반납해도 타이틀과 메모가 초기화되지 않고 남아있습니다.
3명만 순차적으로 사물함을 대여하고 반납할 경우에는 타이틀과 메모가 초기화되는 것 확인했습니다.

### 상황에 대한 스크린샷, 콘솔
<img width="385" alt="스크린샷 2022-10-21 오후 9 05 19" src="https://user-images.githubusercontent.com/62418146/197191789-42048d86-1bfa-499f-927f-4ee4e791c6e5.png">

**Comment by sichoi42** [comment]
버그 상황이 아니라 정상 상황에서도 만료시간 설정 전(`cabinet_status`가 `AVAILABLE`) 상태에서 모두 반납을 했을 때도 `title`과 `memo`가 남아있는 문제가 있습니다. 수정해서 PR 올리겠습니다!
