### ISSUE TITLE
공유 사물함 패널티 상태에서 타 공유 사물함 대여 시 발생한 문제

### ISSUE THREAD

**Issue by aseungbo** [innovationacademy-kr/42cabi#477]
### 버그에 대한 설명
공유 사물함 패널티를 가진 상태에서 타 공유 사물함을 대여했을 때(?) 발생한 문제입니다.
### 상황에 대한 스크린샷, 콘솔
<img width="846" alt="image" src="https://user-images.githubusercontent.com/46778769/197192929-6d8beb43-606f-4bf4-8631-f27f963e82cb.png">

**Comment by HyeonsikBae** [comment]
aws에서 백엔드로부터 유효하지 않은 응답을 받은 것 같습니다
브라우저단에서 502 Gateway 페이지를 받아 렌더하기 때문에 어떤 응답으로 왔는지 확인하기는 힘들 것 같습니다.
https://developer.mozilla.org/ko/docs/Web/HTTP/Status/502
