### ISSUE TITLE
방 제목이 길어지면 위에가 짤리는 현상

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#479]
### 버그에 대한 설명
방 제목이 길어지면 스크롤이 적용되어 아래 내용은 볼 수 있지만 위에가 반쯤 짤립니다.

### 상황에 대한 스크린샷, 콘솔
<img width="428" alt="스크린샷 2022-10-21 오후 9 50 45" src="https://user-images.githubusercontent.com/63849465/197200373-46d87da7-be6c-41d4-ba9f-d3dd6a48e827.png">

**Comment by HyeonsikBae** [comment]
0a4a10afaa1b33e5f9289af32c1662d3c5f21d29

인풋 길이를 14로 제한하였습니다
