### ISSUE TITLE
대여중인 사물함이 없는데 /lent로 진입이 가능한 문제

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#490]
## 버그사항이 담긴 제목
대여중인 사물함이 없는데 `/lent`로 진입이 가능한 문제

### 버그에 대한 설명

아래 사진처럼 대여중인 사물함이 없는데 `/lent`로 진입이 가능합니다.
오류가 발생하는 조건은 다음과 같습니다.
1. 사물함을 대여한다.
2. `/lent`로 진입한 상태로 유지한다.
3. 사물함을 장기 연체한다.
4. 장기 연체로 인해 사물함을 강제반납 당한다.
5. 새로고침 한다.

사물함을 빌리지 않은채로 main 페이지에서 lent 페이지로 넘어가는건 잘 막혀있는 것 같은데, 사물함을 빌린상태로 lent 페이지에 진입하고, 그 상태로 반납처리가 되면 대여중인 사물함이 없는 채로 lent 페이지로 진입이 가능한 것 같습니다...!

### 상황에 대한 스크린샷, 콘솔

<img width="958" alt="스크린샷 2022-10-23 오후 3 48 19" src="https://user-images.githubusercontent.com/83565255/197378404-42c5e0c5-bbc6-441c-b9eb-44c0892bac97.png">

뿐만아니라 대여한 사물함이 없는데 lent로 진입하는 경우,  HTTP Response로 `204 NO_CONTENT`가 클라이언트에게 날라 가야 하는데
아래 사진과 같이 `500 Internal Server Error`가 발생합니다.

<img width="492" alt="스크린샷 2022-10-23 오후 4 03 16" src="https://user-images.githubusercontent.com/83565255/197378820-ab0070b9-4790-47ed-b516-473840c28f60.png">

아래는 backend에서 찍히는 에러 메시지입니다.

<img width="981" alt="스크린샷 2022-10-23 오후 3 49 39" src="https://user-images.githubusercontent.com/83565255/197378828-add9d789-614e-4f22-9cd9-fa084eae2727.png">

**Comment by sichoi42** [comment]
<img width="887" alt="스크린샷 2022-10-23 오후 4 08 15" src="https://user-images.githubusercontent.com/83565255/197378981-fb6fb56a-700b-4e22-b1a1-a85d3bcbf123.png">

일단 500 에러가 발생하는 이유는 backend에서 유저가 빌린 사물함을 조회할 때, 빌릴 사물함이 없으면 `cabinetExtendDto`가 `null`을 받게 되는데, 
이 값이 `null`일 때 예외 처리가 되어있지 않아서 `getLentUsers`에 인자로 `cabinetExtendDto.cabinet_id`를 주어 `null`의 프로퍼티를 읽으려고 시도해서 생긴 오류인 것 같습니다. 
이 부분은 바로 수정하겠습니다!

**Comment by Oris482** [comment]
대여하고 lent 페이지에 있는 상태로 다른 탭 열어서 반납하고 기존 탭에서 새로고침했을 때는 500 에러 받아도 메인으로 튕기는데 강제 반납일 때만 안튕기는 건 왜죠??

**Comment by sichoi42** [comment]
> 대여하고 lent 페이지에 있는 상태로 다른 탭 열어서 반납하고 기존 탭에서 새로고침했을 때는 500 에러 받아도 메인으로 튕기는데 강제 반납일 때만 안튕기는 건 왜죠??

제말이 그말입니다 ㅠㅠ ,,,
조심스럽게 추측하는건 프론트에서 대여중인 사물함이 있는지 없는지 체크를 최초에 main 페이지에 진입할 때만 하기 때문에

### 일반적인 경우
main 진입(대여중인 사물함이 없는 것으로 확인) -> lent 진입 -> 대여중인 사물함이 없으므로 main으로 리다이렉트

### 강제 반납 처리한 경우
사물함 가진채로 lent 진입 -> 강제 반납 -> lent 진입 -> main을 한 번 찍고 간게 아니기 때문에 여전히 사물함을 대여중이라 판단하여 main으로 리다이렉트 x

이런식으로 되는게 아닐까요..?
