### ISSUE TITLE
대여기간 등 기간과 관련된 값 환경변수로 관리 필요

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#498]
대여기간과 이메일 발송 시점 등 시간과 관련된 값이 변경될 여지가 있는데 현재는 모두 하드코딩 되어 있어 관리가 어려운 것 같습니다.
환경변수로 관리할 수 있도록 수정하겠습니다!

**Comment by Oris482** [comment]
프론트도 이 부분 환경변수로 관리하도록 변경하겠습니다.

**Comment by Oris482** [comment]
프론트엔드도 노션에 .env로 설정해야 정상적으로 표시됩니다!
