### ISSUE TITLE
BUG: access_token이 없을 때 응답처리

### ISSUE THREAD

**Issue by YeonSeong-Lee** [innovationacademy-kr/42cabi#513]
## 버그사항이 담긴 제목
access_token이 없을 때 응답처리

### 버그에 대한 설명
access_token이 없을 때 응답처리가 안되어 있습니다. 

반납버튼을 누르면 access_token이 없어서 401(권한없음)으로 실패하지만, 사용자 입장에서 알 수 없습니다.

### 대응방법
 1. 401으로 실패했을 때 재로그인후 재시도
 2. 401응답시 사용자에게 알림

크게 두가지정도에 대응방법이 있을거 같습니다.

### 버그 재현법
-> 로그인 -> 반납창 -> 개발자도구에서 access_token삭제 -> 반납버튼 클릭

### 상황에 대한 스크린샷, 콘솔
![cabi_trivial_bug](https://user-images.githubusercontent.com/62806979/197833684-37b4a1ce-e6ce-42c9-993b-ea2901092813.gif)

### P.S
빈번하게 일어날만한 사항은 아니지만, access_token의 만료기간이 지난뒤에 사용자가 요청할 수 있으니 처리하면 좋아보입니다.

**Comment by Oris482** [comment]
소중한 제보 감사드립니다!
저희가 refresh token을 사용하지 않고 있어서 토큰을 지우고 로그인 페이지로 보내는 방식으로 처리했습니다!
- #516
