### ISSUE TITLE
토큰 만료 시 토큰 만료 alert 창이 여러번 뜸

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42cabi#520]
## 버그사항이 담긴 제목
토큰 만료 시 cabi 페이지에서 새로고침 시 토큰 만료 alert 창이 여러번 뜸

### 버그에 대한 설명
예를 들면 `https://cabidev.42seoul.io/main` 페이지가 렌더링된 후 토큰 만료 시 새로고침 하면 alert 창이 여러번 뜹니다.

### 상황에 대한 스크린샷, 콘솔
<img width="572" alt="스크린샷 2022-10-26 오후 7 10 30" src="https://user-images.githubusercontent.com/27172454/197999737-03eced97-ccfa-40cd-8a72-bdf9f1261631.png">

**Comment by gyutato** [comment]
CabinetTemplate의 useEffect를 하나로 합쳐서 해결했습니다~
