### ISSUE TITLE
email이 가지 않는 버그

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#534]
### 버그에 대한 설명
main에서 email이 제대로 가지 않는 것을 확인했습니다.
확인해보니 환경변수로 이메일을 언제 보낼지 확인하는 부분에서 조금 빠진 부분이 있었던 것 같습니다.
또한 날짜 계산에 대해서도 조금 문제가 있었던 것 같습니다.

**Comment by sichoi42** [comment]
<img width="1418" alt="스크린샷 2022-11-01 오전 11 49 20" src="https://user-images.githubusercontent.com/83565255/199147914-d09c986d-258f-49be-9855-7ef877f060a5.png">

단시간에 동시에 많은 메일을 발송하는 것 때문에 메일 발송에 실패하는 문제가 있습니다. 
비슷한 이슈가 https://stackoverflow.com/questions/39097834/gmail-smtp-error-temporary-block 에도 있어 해결방법을 살펴보니
1. `AWS SES`를 사용하는 방법
2. 메일 발송 사이사이 1초 정도의 딜레이를 주는 방법
이 있는데 1번은 유료인 것 같아 이용이 어려울 것 같습니다.
2번 방법으로 해결해보겠습니다!
