### ISSUE TITLE
사물함 대여 후 로그아웃 없이 탭 껐다가 새로 들어갔을 때 main 으로 들어가지는 문제

### ISSUE THREAD

**Issue by gyutato** [innovationacademy-kr/42cabi#547]
lent로 리다이렉트 되지 않고 있습니다.

**Comment by aseungbo** [comment]
@gyutato 
pages/main.tsx에서 axiosMyInfo 요청을 보내는 로직이 intra_id가 default가 아닌 경우에는 dispatch만 이루어지고 조건에 따라 navigate가 실행되는 로직이 없어서 생기는 그대로 main에 남아있는 것 같습니다!
