### ISSUE TITLE
서버 open/close 방식 개선 필요

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#559]
기존에는 `ServeStaticModule`에서 환경변수 `IS_V3` 값을 통해 `frontend dist(점검 페이지)`를 가져올지, 
`frontend_v3 dist(현재 운영중인 페이지)`를 가져올지 판단하였습니다.
하지만 환경변수는 서버를 재가동해야 반영되기 때문에 `점검 -> 오픈` 상태로 바꿀 때 서버가 online 상태가 되기전에 `502 Bad Gate` 페이지가 클라이언트에게 제공되는 문제가 있습니다.
오늘 오픈 때는 `IS_V3`를 false로 설정해두고 점검페이지를 띄워두다가 서버 오픈 시점에 frontend_v3 버전의 dist를 frontend 디렉토리에 복사하는 식으로 해결했지만 임시 방편으로 처리한 것이라 추후 개선이 필요해보입니다..!
제가 일단 생각하고 있는 방법은 아래 2가지입니다.

1. 기존 방식대로 하되, nginx에서 서버가 offline일 때 클라이언트에게 제공할 페이지를 점검 페이지로 대체한다.
2. deploy라는 디렉토리를 만들고 `ServeStaticModule`이 deploy 디렉토리를 정적 페이지로 관리하게 한다.
    그리고 점검 상태일 때는 이곳에 frontend dist를 올려두고, 오픈 상태일 때는 frontend_v3 dist를 올려둔다.

**Comment by joohongpark** [comment]
1. 서버단에서 환경변수로 해당기능을 제어하는 것은 제거처리 하도록 합시다.
2. 제안하신 방법대로 백앤드 `src` 폴더 내 `deploy` 라는 폴더를 만들고 해당 폴더에 정적 페이지를 배포하는 식으로 진행합시다.
 - CD 스크립트 수정 필요
 - `ServeStaticModule` 설정 수정 필요

**Comment by joohongpark** [comment]
해당 작업은 제가 진행하겠습니다!
