### ISSUE TITLE
[BE] typeorm-transactional 라이브러리 제거

### ISSUE THREAD

**Issue by joohongpark** [innovationacademy-kr/42cabi#562]
`typeorm-transactional` 라이브러리는 사후 지원이 불안정하기 때문에 해당 라이브러리를 제거하는 것이 좋을 듯 합니다.

해당 라이브러리를 도입한 이유는 여러 개의 코드에서 하나의 트랜잭션으로 묶여야 하는 동작을 트랜잭션으로 묶기 위해 사용하였습니다.
Nest.js에서 트랜잭션 데코레이터를 완벽히 지원하지 않아서 도입하였습니다.

현재 해당 라이브러리를 완전히 대체하는 라이브러리가 없기 때문에 다음 방법이 있는 것으로 보입니다.
 - 트랜잭셔널 데코레이터를 직접 만들기
   - 스프링 프레임워크의 사례를 응용해서 만들면 될 듯 합니다. 근데 스프링 프레임워크로 리팩터링 하시면 안 만드셔도 됩니다.
   - `cls-hooked` 라이브러리를 사용해 Nest.js에서 관점지향 프로그래밍의 사례를 응용하여 만들면 될 듯 합니다.
 - 트랜잭션 구조 변경
   - 현재 트랜잭션 적용이 필요한 동작도 여러 모듈 내의 메소드를 호출함.
   - 트랜잭션으로 묶여야 할 동작은 TypeORM 상에서 하나의 메소드로 묶는 방식으로 적용

**Comment by joohongpark** [comment]
`typeorm-transactional` 라이브러리의 기능을 하는 데코레이터를 만들어 보는 쪽으로 결론이 났으며 만약 너무 어려운 작업이라 판단이 되면 리포지터리 내에서 처리하기로 했습니다.
다음 회의까지 `typeorm-transactional` 과 유사한 데코레이터를 만들기 위해 필요한 개념이나 레퍼런스를 조사해 오기로 하였습니다.
@Ssuamje @hunjin-choi @joohongpark @sichoi42 @leedonggyu1848

**Comment by Ssuamje** [comment]
### 0)문제 정의

현재 Cabi 서비스는 백엔드(NestJS)에서 트랜잭션을 관리하는 라이브러리로 TypeORM-transactional을 사용하고있다.
하지만, 사용률과 관심이 저조하다는 점과, TypeORM 자체의 업데이트가 빈번하므로, 이 라이브러리를 지속적으로 사용하는 것은 안정성이 떨어진다고 판단된다. 또한, 도메인을 최대한 나누는 것을 권장하는 NestJS의 프로그래밍 방법으로 백엔드 구조를 구성하였는데, 이로 인해서 트랜잭션의 쿼리가 여러 모듈에서 수행되기 때문에, 트랜잭션이 한 묶음안에서 수행될 수 있도록 설정하고 위 라이브러리를 대체할 수 있는 수단을 찾고자 한다.

### 1)해결 방안 모색

우리가 생각해본 방법은 다음과 같다.
- 현재 라이브러리가 작동하는 방식과 유사하게끔, 우리의 서비스에 맞춰서 Transaction Decorator를 만들자.
- Repository를 새로 만들어서, 우리가 구성한 트랜잭션을 한 묶음으로 구성할 수 있게끔 설정하자.
- 다른 라이브러리를 찾아보자.
Repository를 새로 만들어서 해결하는 방법은, 당장은 수월하게 해낼 수 있으나 큰 경험이 되지는 않을 것 같다는 의견이 다수였다. 그렇다고 트랜잭션을 관리하는 라이브러리(데코레이터)를 만들자니, 난이도가 가늠이 안가는 상황이어서 우리는 일단 일정 기간을 정하고 데코레이터를 직접 만들어보는 방식을 선택했다.
물론 시도하기 전에 필요한 개념들을 정리할 것이고, 또 다른 라이브러리를 찾아보기는 할 것이다.

내가 찾아본 다른 라이브러리를 이용한 해결방법에는 다음과 같이 두 가지가 있다.
1. [QuerryRunner](https://orkhan.gitbook.io/typeorm/docs/transactions#creating-and-using-transactions)
	-> TypeORM 공식 문서에 명기되어 있음.
	-> https://velog.io/@11t518s/NestJs-TypeOrm%EC%97%90%EC%84%9C-Transaction-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0 참조하면 좋을 듯.
2. [TransactionalConnection](https://www.vendure.io/docs/typescript-api/data-access/transactional-connection/)
	-> Typescript에 있는 API의 일종인 듯.
