### ISSUE TITLE
Server가 close 상태일 때 커스텀 점검 페이지

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#564]
### Frontend
- [x] 점검 static 페이지 제작

### Backend
- [x] ec2 nginx config 파일 설정

**Comment by eunbi9n** [comment]
### 이슈 해결 방법
- 기존 usr/share/nginx/html에 존재하는 50x.html의 내용을 수정했습니다.
- png 파일의 경로를 conf 파일에 명시해주어 불러올 수 있도록 했습니다.
### 스크린샷
<img width="707" alt="스크린샷 2022-11-12 오전 12 57 55" src="https://user-images.githubusercontent.com/63849465/201383074-23d90acc-ab8d-463b-888f-0d17f8ca0237.png">
귀여운 점검 페이지 획득. . .
