### ISSUE TITLE
[COMMON] 토큰, 인증 관련 로직 수정

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#591]

**Comment by 42inshin** [comment]
**42HANE repo에서 확인 후 작업하기**
[42HANE링크](https://github.com/innovationacademy-kr/42checkin_v3-backend)
- 미들웨어에서 req에서 온 host주소 담아서 처리하는 방식이었음.
- jwtSignGuard에서 token 생성 및 res.cookie() 로 넘기는 방식.

**Comment by sichoi42** [comment]
<img width="867" alt="스크린샷 2022-12-20 오후 6 23 11" src="https://user-images.githubusercontent.com/83565255/208633987-3d190344-df21-4b19-95f4-eaaed5b3895a.png">

joopark님이 조언해주신대로 `cookieOPtions`의 `domain`에 도메인 주소를 주면, 해당 도메인의 서브 도메인끼리 쿠키 공유가 가능합니다.
위의 경우 [cabi.42seoul.io](http://cabi.42seoul.io/), [api.cabi.42seoul.io](http://api.cabi.42seoul.io/), [dev-api.cabi.42seoul.io](http://dev-api.cabi.42seoul.io/), [dev.cabi.42seoul.io](http://dev.cabi.42seoul.io/)와 쿠키 공유가 가능합니다.

<img width="516" alt="스크린샷 2022-12-20 오후 6 37 27" src="https://user-images.githubusercontent.com/83565255/208634200-78e7b96c-18cc-4780-9d1b-d8ec7adaa9cd.png">
저 방식대로 쿠키에 토큰을 저장하면 클라이언트 브라우저에서 쿠키가 저장된 것을 확인할 수 있습니다.

따라서 지금 방식처럼 `query`에 `access_token` 필드를 통해 토큰 값을 전달하는 대신, 기존 방식대로 `JwtSignGuard`에서 jwt토큰을 생성하여 쿠키에 저장하고, 클라이언트로 리다이렉트 시켜주기만 하면 클라이언트 측에서 이를 확인할 수 있습니다.
클라이언트 측에서도 `query`에 있는 `access_token`을 확인할 필요 없이 쿠키에 있는 토큰을 통해 api 요청을 보낼 수 있습니다.

하지만 반대로 서버측에서 클라이언트의 쿠키에 있는 토큰을 추출해는건 어려울 것 같습니다. 따라서 이 부분은 지금 방식처럼 클라이언트에서 api 요청을 보낼 때 `Request Header`에 `Bearer token`을 담아서 보내면 서버측에서 `fromAuthHeaderAsBearerToken` 함수를 통해 토큰값을 확인하도록 해야합니다.

**Comment by sichoi42** [comment]
추가로 이제 프론트는 `S3, Cloudfront`를 통해 배포하기 때문에 배포 환경에서 이용했었던 `ServeStaticModule` 모듈도 제거해야합니다!
