### ISSUE TITLE
[BE] 격리 수준 serializable, X Lock 적용 문제

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#595]
### 작업 설명

현재 대여/반납에서의 무결성 문제를 해결하기 위해 트랜잭션 격리 수준을 최고 수준인 `SERIALIZABLE`로 설정하고, `SELECT` 시에 `X Lock`을 걸도록 조치가 되어 있습니다.
하지만 이렇게 조치한다면 당장에는 동시 이용자가 그리 많지 않아 문제가 없지만,
여러명의 클라이언트가 동시에 요청을 할 때 작업들이 순차적으로 처리가 되기 때문에 성능 면에서 잠재적인 문제가 있는 상황입니다.
`SERIALIZABLE` 격리 수준과 `X Lock`을 거는 방식을 완화하면서 하나의 사물함에 정원을 넘어서는 대여 요청이 이루어지는 것을 방지할만한 방식을 도입하여 해결이 필요합니다.

### 접근 방법

현재는 `DDL`문에서 `Trigger`를 설정하여 `INSERT` 문 수행 시, 정원을 넘어서는 요청이라면 해당 트랜잭션을 롤백하는 방안이 대안으로 나왔지만 이 역시 성능 면에서 이슈가 있기 때문에 그 외에 다른 대안도 고려가 필요합니다.
또한 어느 환경에서나 문제 없이 동작을 보장하기 위해서는 최대한 코드 상에서 수정이 가능한 방안으로 접근이 필요합니다.

**Comment by Ssuamje** [comment]
### 0)문제 정의
Cabi 서비스에서는 MariaDB를 사용하고 있습니다. MariaDB의 기본 격리수준 설정 값은 Repeatable-read이고, 
이 격리수준에서 트랜잭션에서 읽은 값은 그 트랜잭션이 커밋/롤백될 때까지 유지됩니다.

이 때, 우리 서비스에서 3명까지 이용가능한 캐비넷에 6명의 클라이언트가 동시다발적으로 대여신청을 진행하게 되는 경우, 
각자의 신청시의 대여 유저 수를 기준으로 대여를 하게 되므로 정원을 초과한 인원이 대여를 하게 되는 문제가 발생합니다.

<img src="https://velog.velcdn.com/images/sichoi/post/dc823ff5-dcb3-40a5-af38-145730b75398/image.svg" width="400px" alt="transaction_problem" />

(출처 : [sichoi님 블로그]( https://velog.io/@sichoi/%EB%8F%99%EC%8B%9C-%EB%8C%80%EC%97%AC%EB%B0%98%EB%82%A9-%EB%AC%B8%EC%A0%9C))

이에 대한 해결책으로, 기존 Cabi 팀에서는 트랜잭션의 격리수준(Isolation Level)을 
Serializable(트랜잭션이 끝날 때 까지 다른 트랜잭션에서 테이블에 접근을 막음)로 설정, 트랜잭션 단순화로 문제를 해결했었습니다.

하지만 트랜잭션의 기준이 되는 필요한 동작들의 로직이 중간에 빠진 점과, Serializable 격리수준은 서비스 규모가 커졌을 때를 감안하면 비효율적이고 비용이 높아질 여지를 갖고 있으므로 이전과 같이 Repeated-read로 격리 수준을 낮추고자 합니다.
한편, Repeated-read로 격리 수준을 설정하면, 상술한 여러 트랜잭션에 의한 동시성 문제가 발생할 수 있습니다.

##### 초과 대여 문제
공유 사물함(2/3)에 대여를 신청하는 트랜잭션 A, B 는 순차적이고, 그 시기가 겹치는 트랜잭션이라고 하겠습니다.
- A가 대여 중인지 확인한다(SELECET).
- A가 확인한(SELECT) 사물함의 인원 수는 2/3이다.
- B가 대여 중인지 확인한다(SELECT).
- A가 사물함을 대여한다(INSERT).
- B가 확인한(SELECT) 인원 수는 2/3이다.
  -> 왜냐하면, Repeated-read는 동일한 트랜잭션 내에서 동일한 결과(undo값 참조)를 보장하기 때문이다.
- B가 사물함을 대여한다(INSERT).
- 위 결과로 인해, 결과적으로 두 트랜잭션이 커밋된 후에, 사물함의 대여상태가 (4/3)이 되는 문제가 발생합니다.

### 1)방법 찾기
현재 대여 트랜잭션의 경우, INSERT가 마지막 동작으로 끝나므로 대여 시에 검증을 진행하기에는 힘들어보입니다. 
대안에는 무엇이 있을까요?

##### 내 생각
로깅을 추가해서, 대여를 하고 로깅을 하는 동안 Lock을 거는 방법은 어떨까?
-> INSERT시에 X-Lock을 걸고 대여 여부에 대해 로그를 서버 로그 테이블에 남긴다.
이 동안에 다른 트랜잭션에서는 로깅이 끝날 때까지 대기하게 되고,
앞의 트랜잭션이 커밋한 후에 락을 해제, 이후의 트랜잭션이 로깅을 시작할 때 서버에 로깅이 되어 있는지 여부를 체크하여
만약 로깅이 됐다면 롤백한다.

하지만 위 방법은 우리가 하려는 ‘정확한 동작과 최적화’라는 의도에 걸맞은 지 제대로 따져보아야 합니다. 
또한, X-Lock을 걸어서 트랜잭션의 무결성을 보호하려는 것은 사실상 Serializable 고립수준과 다를 바 없는 방식이라는 생각이 듭니다.
(결국 한 트랜잭션이 끝날 때 까지 다른 트랜잭션은 대기상태이기 때문에).

##### 낙관적 락(Optimistic Lock)
낙관적 락은 수정할 때 내가 먼저 이 값을 수정했다고 명시하여 다른 사람이 동일한 조건으로 값을 수정할 수 없게 하는 개념입니다. 
낙관적 락은 app에서 DB 충돌을 잡아줘야 한다는 점에서 기존의 우리가 사용하던 방식(비관적 락)과 다릅니다.

적용해보자면, version이라는 새 컬럼을 cabinet_info에 추가해서, 같은 버전으로 업데이트하려는 경우 그 트랜잭션을 취소하는 방법이 있습니다.
-> 첫 번째 트랜잭션에서 2에서 3으로 업데이트하고, 이후의 트랜잭션이 3으로 똑같이 업데이트하려할 때 취소

로깅 동작을 추가해서 락을 거는 것이 아닌, 컬럼을 하나 더 추가해서 마지막에 검증하는 방식이어서 더 효율적이고 깔끔해보입니다. 
저는 단순히 트랜잭션의 동작 안에서 모든 검증이 이뤄져야한다고 생각하고 있었는데, 그러지 않아도 된다는 점을 알게 되었습니다.

한편, 비관적 락은 트랜잭션에서 실패했을 시 롤백이 가능하지만, 낙관적 락의 경우 일일히 app에서 체크하고, 수정해줘야한다는 단점이 있습니다. 
하지만 다르게 생각해보면, 충돌이 많이 일어나지 않는 서비스에 적용하면 적절한 방법이 될 수 있다는 얘기이고, 
우리 서비스의 경우, 공유 사물함에 여러 명이 동시에 신청하는 경우는 극히 드물기 때문에, 낙관적 락을 적용해보면 좋을 것 같습니다.

혹시라도 오개념이나 부족한 부분이 있으면 말씀해주세요!

**Comment by sichoi42** [comment]
https://velog.io/@znftm97/%EB%8F%99%EC%8B%9C%EC%84%B1-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0-V1-%EB%82%99%EA%B4%80%EC%A0%81-%EB%9D%BDOptimisitc-Lock-feat.%EB%8D%B0%EB%93%9C%EB%9D%BD-%EC%B2%AB-%EB%A7%8C%EB%82%A8

저희와 비슷한 문제를 겪어 `Optimistic Lock`을 이용하여 문제를 해결하려고 시도했던 글입니다.
결론만 말씀드리자면 `Optimistic Lock`만으로는 문제를 완전히 해결하기는 어려울 것 같습니다.

**Comment by sichoi42** [comment]
https://velog.io/@znftm97/%EB%8F%99%EC%8B%9C%EC%84%B1-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0%ED%95%98%EA%B8%B0-V1-%EB%82%99%EA%B4%80%EC%A0%81-%EB%9D%BDOptimisitc-Lock-feat.%EB%8D%B0%EB%93%9C%EB%9D%BD-%EC%B2%AB-%EB%A7%8C%EB%82%A8

저희와 비슷한 문제를 겪어 `Optimistic Lock`을 이용하여 문제를 해결하려고 시도했던 글입니다.
결론만 말씀드리자면 `Optimistic Lock`만으로는 문제를 완전히 해결하기는 어려울 것 같습니다.
Optimistic Lock을 사용한다고 해도 `S Lock`이나 `X Lock`을 사용하지 않는 것은 아닙니다. 
트랜잭션 격리수준이 `READ_COMMITTED`이상이면 SELCT에서 `S Lock`이 걸리고, UPDATE에서 `X Lock`이 걸립니다.
따라서
1. 사물함을 대여중인 인원수 조회 (`S Lock`)
2. lent 테이블에 INSERT
3. 캐비넷 상태 변경 (`X Lock`)
위와 같은 순서로 트랜잭션이 동작하고, 하나의 Row에 대해서 `S Lock`과 `X Lock`을 모두 걸기 때문에 데드락이 발생합니다. (실제로 테스트 결과 발생했습니다.)

**Comment by sichoi42** [comment]
따라서 동시 대여 문제를 아래와 같은 방식으로 우회하여 해결하는 방법을 제시합니다..!
1. 데드락 발생한 경우
예전에도 잠깐 얘기가됐던 방식인데, 데드락 문제를 굳이 해결하지 않고, 데드락 발생 시 다시 대여 요청을 시도하는 것입니다.
다시 요청을 보냈을 때 정원이 남았으면 요청에 성공할 것이고, 정원이 꽉찼으면 요청에 실패할 것입니다.

3. 데드락이 발생하지 않은 경우
이 경우엔 동시에 대여를 했을 때 모든 요청이 성공으로 처리될 것입니다. 즉 정원을 넘어서는 대여 요청이 성공한 경우입니다.
이때는 `Trigger`나 `EventSubscriber`등을 이용하여 정원 초과를 감지하도록 하고, 감지가 되면 초과분에 대해서 대여 취소를 하는 식으로 처리가 가능할 것 같습니다.

**Comment by hunjin-choi** [comment]
1. mysql에서 지원하는 여러 제약조건([참고블로그](https://chartworld.tistory.com/16)) 중 트리거 활용
2. 트리거 동작방식에 대해 잘 모르고, 무한루프 위험이 있다고 해서([구루비1](http://www.gurubee.net/article/86370))([구루비2](http://www.gurubee.net/lecture/2057)) 다른 방법 찾아보기로.
3.  [conditional insert?](https://stackoverflow.com/questions/16636698/do-conditional-insert-with-sql)
4. 위의 방식으로 하면 중복 insert 문제 없어짐. dead lock 발생 안함. 하지만 where 말고 having을 쓰면 dead lock 발생. 다른 방법 찾아보기로.
5. 비슷한 문제에 대한 해결책([스택오버플로우](https://stackoverflow.com/questions/264807/mysql-insert-race-condition))([구루비](http://wiki.gurubee.net/pages/viewpage.action?pageId=22904839)) 요약하면 pk를 수동으로 넣어주고 DBMS의 pk중복 체크 기능 활용. insert시 pk가 중복이면 해당 트랜잭션 롤백.
6.
