### ISSUE TITLE
✨ 42cabi 데이터 설계

### ISSUE THREAD

**Issue by subin195-09** [innovationacademy-kr/42cabi#6]
### 로그인

- 관리자 인트라 ID에 관리 권한을 부여한다.
- 유저는 42 OAUTH 로 로그인한다.
- 로그인 시에, 인트라 ID, Email, 휴대전화 번호가 저장된다.
- 유저의 사물함 ID를 조회하여 대여 페이지 또는 반납/연장 페이지로 이동시켜줄 수 있다.
- 관리자 권한이 있는 경우, 별도의 관리자 메뉴를 사용할 수 있다.

### 대여

- 유저는 사물함의 사용여부를 알 수 있고, 빈 사물함을 골라 대여할 수 있다.
- 각 사물함은 건물위치, 층, 구역, 사물함번호, 이전사용자, 현재사용자, 대여일, 만료일에 대한 정보를 가지고 있다.
- 유저가 사물함을 선택한 후, 현재사용자는 유저의 아이디로 바뀌고, 대여일, 만료일의 정보를 입력시켜준다.

### 반납

- 사물함의 연장유무 정보를 확인하여, 연장 버튼이 활성화 또는 비활성화가 된다.
- 반납 버튼을 누르면 사물함의 현재 사용자가 이전 사용자로 변경된 후, 현재 사용자, 대여일, 만료일, 연장유무는 초기화된다.

### 연장

- 연장 버튼을 누르면 현재 일을 기준으로 만료일이 4주간 연장이 되고, 연장유무의 정보를 변경시켜준다.

**Comment by subin195-09** [comment]
[ERD 설계](https://www.erdcloud.com/d/dfbB6j63ATQFnaqLZ)

**Comment by kamg2218** [comment]
<img width="962" alt="스크린샷 2021-12-20 오후 7 48 04" src="https://user-images.githubusercontent.com/57984608/146755490-9ea905be-dcd1-4210-bb6d-cc6bd4a09dfa.png">
