### ISSUE TITLE
[COMMON] 기존 v3 및 admin API 정리

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#638]
### 작업 설명

기존 backend에서 설정해놓은 v3가 달린 API를 정리하고,
admin의 API를 정리합니다.

ADD: Frontend Axios 최신화된 API로 완전 대체하고 사용하지 않는 모듈들 정리

### 접근 방법

피어 코딩으로 정리

**Comment by sichoi42** [comment]
- `/api/lent/:cabinet_id`에서 대여기간이 얼마남지 않은 공유 사물함 대여 시 Exception에 대한 swagger 명세 추가 필요.
- logout API가 삭제 예정이므로 swagger 상에서 제거 필요.

**Comment by sichoi42** [comment]
- 새로 추가될 `/auth/is_login` API에 대한 명세 추가 필요
