### ISSUE TITLE
[FE] v4 main 안보이는 버그

### ISSUE THREAD

**Issue by 42inshin** [innovationacademy-kr/42cabi#640]
### 버그 설명

모든 풀리퀘가 끝났으나 문제가 있는 코드가 있었습니다.

### 재현 방법

/main 에 들어갔을 때 안보이는 현상입니다.

### 기대했던 정상 동작

정상적으로 컴포넌트가 보여야합니다.

**Comment by Oris482** [comment]
Closed by PR
- PR #641
