### ISSUE TITLE
[FE] v4 set_expire_available한 캐비넷 색상 이슈 발생

### ISSUE THREAD

**Issue by SeyoungCho** [innovationacademy-kr/42cabi#642]
### 버그 설명

v4 dev merge 후 status가 SET_EXPIRE_AVAILABLE한 캐비넷에 대한 색상이 정확히 반영이 되지 않은 것을 발견하였습니다.

### 재현 방법

회색 색상은 정상적으로 나오지만 다음과 같이 아이콘 및 텍스트 색상이 반전되지 않습니다.
(원래는 검은색 아이콘, 검은색 텍스트)
<img width="100" alt="image" src="https://user-images.githubusercontent.com/45449387/209307565-18b6e348-05f1-4d32-94ee-1b955150c538.png">

### 기대했던 정상 동작

<img width="168" alt="image" src="https://user-images.githubusercontent.com/45449387/209308533-3e6cee46-6bbb-40da-8ff9-097f4bf08e8a.png">

**Comment by Oris482** [comment]
- PR #643
