### ISSUE TITLE
[FE] 중복된 이미지 정리 및 네이밍 정리

### ISSUE THREAD

**Issue by 42inshin** [innovationacademy-kr/42cabi#652]
### 버그 설명

현재 중복 이미지들이 여러 이름들으로 `assets/images/` 저장되어 있습니다
중복된 이미지들을 삭제하고 하나의 이미지를 사용하는 걸로 바꿔야 되겠습니다.

이름이 정해지면 각 파일들에서 해당 이름으로 변경 후 pull requests하도록 하겠습니다.

댓글 남겨주세요~~

### 재현 방법

함께 사용중인 이미지들 확인 후, 하나의 이름으로 결정하고 나머지는 삭제하는 식으로 정리하면 될 것 같습니다.

1. 공유사물함, 개인사물함, 동아리사물함 icon의 이름을 정해주세요!

### 기대했던 정상 동작

이름이 정해지면 한번에 처리하도록 하겠습니다.

**Comment by 42inshin** [comment]
중복된 이미지는 `"공유사물함, 개인사물함, 동아리사물함"` 아이콘 입니다. 
사용된 이름으로는 
- privateCabinetType, shareCabinetType, circleCabinetType 
- soloIcon, groupIcon, clubIcon
이며, 유사항목으로
- single_circle, group_circle, club_circle
도 있습니다.

**Comment by 42inshin** [comment]
이미지에는 네이밍 방식을 정하지 않아서 여러방식으로 적었었는데, 이것도 카멜케이스로 하는게 좋겠네요.
이 글 보신거 확인되면 한번에 정리하도록 하겠습니다.

**Comment by Oris482** [comment]
Icon이랑 Logo 단어 선택도 헷갈리더라구요

**Comment by 42inshin** [comment]
> Icon이랑 Logo 단어 선택도 고민입니다

그러게여 하다보니 이미지도 컨벤션을 정해야하겠더라고요 ㅎㅎ 오는 주에 한번 모여서 정리 싹 하고 새출발하는거 어떠십니까?

**Comment by Oris482** [comment]
privateIcon, shareIcon, circleIcone

**Comment by Oris482** [comment]
circle 타입은 inshin님께서 css 작업 후 제거할 예정입니다.
해당 작업 진행 후에 PR 부탁드릴게요!
