### ISSUE TITLE
[FE] BUG: 대여, 반납 후 캐비넷 정보, 상세정보 미반영 버그

### ISSUE THREAD

**Issue by SeyoungCho** [innovationacademy-kr/42cabi#750]
### 버그 설명

대여, 반납 후 캐비넷 정보, 상세정보 미반영 버그

### 재현 방법

<img width="282" alt="image" src="https://user-images.githubusercontent.com/45449387/210509765-68f7aca3-bdd9-44b3-9a4c-c6517e3cc537.png">
위 이미지처럼 대여 완료 후에 사용자 이름이 반영이 안됩니다. 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/45449387/210509869-07d9682b-2c3e-43c2-9002-8ca2d6fa8e2b.png">
또한 위 이미지 처럼 대여 완료 후 인트라 아이디가 캐비넷 아이콘에 미반영됩니다. 
<img width="287" alt="image" src="https://user-images.githubusercontent.com/45449387/210509988-59e35b2b-a03a-4492-b7a6-c52d359ecfb2.png">
반납 직후에 상세보기 페이지에도 빈 사물함처럼 보이지 않습니다

### 기대했던 정상 동작

대여, 반납 직후 상세보기와 메인페이지 캐비넷 아이콘이 대여, 반납 완료에 대한 변화를 정상적으로 반영해야 합니다.

**Comment by 42inshin** [comment]
해당 이슈는 해결된 관계로 닫도록 하겠습니다.
