### ISSUE TITLE
[FE] BUG: 유효하지 않은 토큰을 지닌 경우, 무한으로 alert 창 생성되는 이슈

### ISSUE THREAD

**Issue by 42inshin** [innovationacademy-kr/42cabi#754]
### 버그 설명

토큰 값이 유효하지 않은 경우 alert 창이 뜨는데, 그뒤로 login 페이지로 가고도 계속 alert 창이 뜨는 상황 발생합니다.

### 재현 방법

토큰을 강제로 변경시키면 해당 버그가 발현됩니다.

### 기대했던 정상 동작

alert창이 한번만 뜨고, 그뒤로 login페이지로 이동 후 정상 작동이 되어야 합니다.

**Comment by sichoi42** [comment]
https://www.notion.so/hyunja/522-c8ba65e9bfb24125bd19678db5861f08
예전에 프론트 3차분들이 해결하셨던 이슈로 기억하는데 혹시 배포 환경에서도 문제가 발생하나요?

**Comment by 42inshin** [comment]
> https://www.notion.so/hyunja/522-c8ba65e9bfb24125bd19678db5861f08
> 
> 예전에 프론트 3차분들이 해결하셨던 이슈로 기억하는데 혹시 배포 환경에서도 문제가 발생하나요?
> 
> 로컬에서만 alert가 여러번 떠서 무시하고 넘기셨었던걸로 기억합니다..!

오호 저기서 발생하는거였군요 ㅎㅎ 
저희 로그인페이지 라우터를 / -> /login 으로 바꾸기로 했는데 axios instance는 수정을 안해서 발생한 문제인가보네요

**Comment by Oris482** [comment]
- #755
