### ISSUE TITLE
[BE] Test code 추가

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi#793]
### 작업 설명

test code를 추가합니다.

### 접근 방법

각자 모듈을 나누고 테스트 코드를 작성합니다.

**Comment by Ssuamje** [comment]
각자 맡으신 파트를 브랜치를 나누어서 진행한 후에 리뷰, 머지하면 될 것 같습니다!
브랜치 예시) be/dev/test_본인모듈/#793

**Comment by Ssuamje** [comment]
인증관련 커밋은 이슈번호를 잘못 적었습니다..

**Comment by kenu** [comment]
![image](https://user-images.githubusercontent.com/718691/213130106-51648fc6-b55b-4406-a0b6-781bf7222378.png)
테스트 관련한 좋은 글이 있어서, 공유하면서 응원합니다.
2023년 새해 복 많이 받으세요.
요즘 저는 https://painterus.com 서비스와 관련된 일을 하고 있습니다. #뭔가광고같아서미안합니다.
2021년 멘토단에 있었던 허광남입니다.

**Comment by Ssuamje** [comment]
좋은 글 공유 감사드립니다!! 😊

**Comment by sichoi42** [comment]
헉 좋은 글 공유 감사합니다!! 새해 복 많이 받으세요! 😄

**Comment by Oris482** [comment]
이런 식으로 함수를 분리하면 테스트하기에 확실히 편해지겠네요!
좋은 글 감사합니다!!
