### ISSUE TITLE
[FE] FEAT: 모바일 섹션 이동 스와이프 기능 구현

### ISSUE THREAD

**Issue by oyhoyhk** [innovationacademy-kr/42cabi#796]
### 작업 설명

모바일 화면에서 캐비넷 섹션에서 스와이프를 하면 현재 섹션이 바뀌는 기능을 추가하였습니다.

### 접근 방법

onTouchStart
onTouchEnd
이벤트의 changesTouched[0] 프로퍼티를 이용하여 오프셋 값을 구해서 해결했습니다.

**Comment by 42inshin** [comment]
스와이프 기능 Layout -> MainPage로 이동을 위해 ReOpen 하였습니다
