### ISSUE TITLE
[FE] 리팩토링 과제 정리

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi#812]
### 작업 설명

1. 변하지 않은 상태와 props를 가진 컴포넌트의 리렌더링 없애고 변수나 함수 재생성 방지
2. 비동기 데이터 recoil 자체 기능 혹은 react-query로 변경 

### 접근 방법

1. React.Memo, useMemo, useCallback 적절하게 적용하여 수정합니다.
2. selector의 asnyc와 React.Suspense, React.lazy, useTrasition 등을 활용하여 수정합니다.

**Comment by SeyoungCho** [comment]
꼭 리팩토링이 필요한 사안입니다. 이번 기회에 저도 맹목적으로 state를 사용하는 습관을 고쳐보겠습니다. 1번을 맡아서 해보고싶은데 괜찮을까요

**Comment by Oris482** [comment]
나중에 리팩토링할거 안까먹으려고 일단 리스팅 해두는 중입니다!
테스트팀, 리팩토링팀으로 나눠서 지식 공유하고 같이 메인 + 어드민 통합 작업들어가도 괜찮아보이네요.
