### ISSUE TITLE
[FE] FIX: 지도 스와이프 방향 수정 필요

### ISSUE THREAD

**Issue by oyhoyhk** [innovationacademy-kr/42cabi#835]
### 버그 설명

지도 화면에서 스와이프할 때 층이 바뀌는 방향이 반대로 가는 편이 사용자들에게 더 익숙할 것 같아 수정이 필요합니다.

### 재현 방법

스와이프

### 기대했던 정상 동작

오른쪽에서 왼쪽으로 하면 층++

왼쪽에서 오른쪽으로 하면 층--

**Comment by 42inshin** [comment]
지도 데이터에서 2층 테라스를 둘로 나눈것 위치가 바꼈습니다. 이 작업하시면서 그부분도 수정부탁드릴게요!
