### ISSUE TITLE
[COMMON] FEAT: 관리자 페이지 검색 기능 구현

### ISSUE THREAD

**Issue by oyhoyhk** [innovationacademy-kr/42cabi#868]
### 작업 설명

관리자 페이지에서 검색창에서 입력을 할 때마다 입력된 값에 대한 get요청을 보내면

서버에서는 해당 데이터를 두 가지 기준으로 판단하여 그에 따른 필요한 결과 값을 보내주어야 합니다.

숫자만 데이터로 보내면 해당 숫자에 해당되는 모든 사물함 정보를,

영어 단어로 시작하는 데이터를 보내면 `해당 단어로 시작하는 모든 유저` 그리고 `그 유저들이 이용하는 캐비넷 정보` 를 보내주어야 합니다.

<img width="292" alt="Screenshot 2023-01-20 at 8 27 19 PM" src="https://user-images.githubusercontent.com/55866366/213684839-a2fccc78-6e71-49e4-aa3b-1421effd5e9c.png">
<img width="1013" alt="Screenshot 2023-01-20 at 8 30 30 PM" src="https://user-images.githubusercontent.com/55866366/213685234-4f27e9d2-04de-44cd-9c89-3f679473cc21.png">

### 접근 방법

프론트엔드 단에서는 onChange 이벤트를 이용해 input.tag의 값이 바뀔때마다 요청을 합니다.
이 때 디바운스 혹은 쓰로틀링 기법을 이용해 사용자가 어느 정도 입력을 했을 때에만 요청을 하게 하여 부하를 최대한 줄입니다.

**Comment by Ssuamje** [comment]
해당하는 모든 유저에 대한 정보를 보내주는 것보다, 해당하는 유저나 캐비닛의 개수를 정해놓은 상태(10개 정도)로 보내는 방식으로 우선 처리해보겠습니다!

**Comment by 42inshin** [comment]
getUserListByIntraId'와 'getCabinetListByVisibleNum' 는 제가 알고 있기론 정확한 값을 전달해야지만 보입니다.
앞의 기능은 intraId 값이 완벽히 일치해야 하며,  뒤의 기능은 층 정보와 사물함번호를 같이 전달해야하는 것으로 알고 있습니다

**Comment by Ssuamje** [comment]
아닙니다! 
getUserListByIntraId는 param으로 전달되는 스트링을 가지고 있는 모든 유저를 가져옵니다!
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/105692206/213844305-08006bec-bf3d-4d0d-8dca-d0371769e6d1.png">

그리고 getCabinetListByVisibleNum 의 경우에는 해당 숫자를 포함한 캐비닛(고유한 cabinet_id가 아닌, 각 층에서 우리가 실제로 볼 때의 캐비닛 번호를 갖는 캐비닛)들에 대한 정보를 전달해줍니다!
<img width="1387" alt="스크린샷 2023-01-21 오후 2 03 34" src="https://user-images.githubusercontent.com/105692206/213844419-474bdcc5-cce1-4367-96fc-d424175c01ce.png">

**Comment by 42inshin** [comment]
오호..... 벌써 만들어져 있었는가보네요?! 
이전 관리자 페이지 검색에서는 저렇게 안됐었는데! ㅎㅎ 
그럼 바로 만들수 있겠네요
감사합니다 ㅎㅎ
