### ISSUE TITLE
[BE] 개발 단계에서 자신을 관리자로 설정하는 API 추가

### ISSUE THREAD

**Issue by sichoi42** [innovationacademy-kr/42cabi#870]
### 작업 설명

개발 단계에서 관리자용 토큰을 받기 위해서는 현재 아래 프로세스를 따라야합니다.
1. 구글 로그인을 한다.
2. DB에서 admin_user 테이블의 role 필드 값을 1로 바꿔준다.
3. 다시 구글 로그인을 한다.
4. admin_access_token이 발급된다.

그러나 수동으로 DB 필드를 수정하는 것이 번거로우므로 개발 모드 한정 자기 자신을 관리자로 설정하도록 하는 API를 추가하겠습니다.

### 접근 방법

1. develop이라는 모듈을 생성한다.
2. develop 모듈에 자기 자신을 관리자로 등록하는 API를 추가한다.
3. backend 환경변수 중 SET_ADMIN이라는 값이 true인 경우에만 develop 모듈을 인스턴스화시키도록 설정한다.

**Comment by Ssuamje** [comment]
이 방식대로 진행하게 되면 dev 서버에 진입해서 admin 로그인을 시도하는 모든 유저가 관리자가 될 수 있는 것 아닌가요..?

이전에 최고관리자가 일반관리자를 설정할 수 있게끔 하는 방식을 생각했었는데 이 방식은 어떠신가요?

**Comment by sichoi42** [comment]
실제 운영할 때가 아니라 '개발 단계'에서 적용될 API입니다!
개발 단계에서 기능이 잘 동작하는지 확인하려고 어드민 토큰을 만들 때마다 수동으로 설정하는게 불편하니, 스스로 관리자로 설정할 수 있도록하기 위함이에요.
메인 서비스에서 밴 해제하는 API랑 같은 맥락이라고 보시면 됩니다!

**Comment by Ssuamje** [comment]
이해했습니다!

**Comment by Ssuamje** [comment]
추후에 구현하게 될 '최고 관리자가 승인 대기 유저를 일반 관리자로 승격' API를 감안해서, Manage라는 이름으로 변경 후에, DEV 환경 변수가 있을 경우 '본인 스스로의 권한을 일반/최고 관리자로 설정', 그 외에는 '인자로 입력한 유저를 일반 관리자로 설정' 할 수 있게끔 구현해보겠습니다!
