### ISSUE TITLE
[BE] 관리자 행동 로깅 모듈 및 DB 구현

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#919]
### 작업 설명

관리자 서버에서 각  관리자가 어떤 행동을 헀는지에 대한 정보를 담을 DB 테이블을 설계 및 생성하고,
이 테이블에 맞추어 관리자 행동 로깅 모듈을 구현하고자 합니다.

### 접근 방법

추가적인 논의가 필요할 듯 하지만, 다음과 같은 방법을 생각해봤습니다.
(변경 및 태클 항시 환영)

* DB
테이블 명 : admin_log

컬럼 : 
admin_log_id(로그의 고유 값 - int),
admin_user_id(이메일 아이디 부분 - varchar(32..?)),
admin_lent_id(대여시켰을 때 lent 테이블의 lent_id),
admin_log_id(반납시켰을 때 lent_log 테이블의 log_id),
admin_ban_id(밴-언밴 시켰을 때 ban_log 테이블의 ban_log_id),
admin_log_time(해당 행동이 기록된 시간)

단순 유저 정보, 열람은 굳이 로그를 남길 필요가 없다고 생각하고, 
어드민 권한 부여에 관한 로그는 현재 관리 수월한 수준의 크기여서 굳이 필요하지는 않다는 생각이 듭니다.

* 로깅 
처음에는 로깅하고자 하는 어드민의 메서드들에 데코레이터를 달아주어서 DB에 찍는 것을 생각하였는데,
데코레이터를 사용해서 DB에 데이터를 찍는 것이 괜찮은지 잘 모르겠습니다. (진짜 모름)
만약 통용될 수 있는 방식이라면, 위와 같은 방식이 좋아보이고
아니라면 특정 메서드들에서 트랜잭션에 로깅 메서드를 같이 묶어야하지 않을까 싶습니다.

만약 데코레이터 방식을 채택한다면 저는 다음과 같은 방식이 떠오릅니다.

1. admin_access_token의 payload를 이용, 해당 adminUser의 email을 가져오기.
2. 각 어드민 모듈의 메서드의 결과 값에 따라 위 컬럼 DTO에 맞춰서 쿼리 날림

필요하다면 모듈별로 미들웨어를 만들어보는 것도 좋을 것 같습니다!

읽어보시고 의견 편하게 남겨주세요!! ☺️

**Comment by sichoi42** [comment]
대여했을 때, 반납했을 때, 밴 했을 때 로그를 하나의 테이블에 저장하게 되면, 세가지 중 하나를 했을 때 나머지는 null로 설정이 될거라 비효율적일 것 같습니다.
DB에 로그를 저장한다고 한다면 `admin_lent_log`, `admin_return_log`, `admin_ban_log` 등 각 상황에 맞는 테이블을 만들어서 관리하는 건 어떨까요?

**Comment by oyhoyhk** [comment]
로그를  어떻게 뿌려줄지를 프론트 쪽에서 먼저 정해야 할 것 같아요
그보다 로그 테이블이 3개가 늘어나는건 너무 많아 보이는데
하나의 테이블에서 
|사용(플래그)|대상 id정보|대상 캐비넷 정보|
|-----------|----------|--------------|
|     대여(0)  |yooh 혹은 id|   2F-105.      |    
|     반납(1)  |sanan 혹은 id|   3F-25.      |    
|     밴(2)  |sichoi 혹은 id|   4F-55.      |    

이런 식으로 관리하는건 어떤가요?

**Comment by Ssuamje** [comment]
오 플래그 쓰는 거 저는 좋아보입니다!!
차후에 기능이 추가되더라도 enum만 붙이면 될 것 같아요

**Comment by eunbi9n** [comment]
https://github.com/innovationacademy-kr/42cabi/issues/174
#174
