### ISSUE TITLE
[BE] 어드민 페이지 검색 시 검색된 유저의 대여 정보 받아오는 API 구현

### ISSUE THREAD

**Issue by Ssuamje** [innovationacademy-kr/42cabi#921]
### 작업 설명

자동완성시에 나열되는 유저들의 대여정보를 받아오는 API를 만듭니다.

### 접근 방법

UserInfoDto -('{user_id, intra_id}')의 배열로 담겨오는 현재의 이름 검색기능의 반환값을 기준으로,
해당 user_id를 키값으로 한 대여정보의 배열을 가져오는 방법을 생각해보았습니다.

**Comment by sichoi42** [comment]
```
{
     userDto[],
     cabinetDto,
}
```
위와같은 정보를 응답하도록 하겠습니다.
