### ISSUE TITLE
:bug: 연장버튼 비활성화 기준 변경

### ISSUE THREAD

**Issue by kyoshong** [innovationacademy-kr/42cabi#96]
기존 : 연장 시점 + 7 일 되면서 기한이 줄어드는 현상
수정 : 연장일이 더 적다면 연장버튼 비활성화

**Comment by Hyunja27** [comment]
방금 dev branch에 수정사항 반영하여 올려두었습니다. AWS 상 dev 쪽에도 CI / CD 처리 해두었으니, 확인해주시면 될 것 같아요.
